<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="RITAM-BHATTACHARYA" failures="10" tests="27" name="runner.RunnerTest" time="280.727" errors="2" timestamp="2025-07-30T09:32:22 IST" skipped="0">
  <testcase classname="runner.RunnerTest" name="runScenario" time="13.001"/>
  <testcase classname="runner.RunnerTest" name="runScenario" time="11.458"/>
  <testcase classname="runner.RunnerTest" name="runScenario" time="11.782"/>
  <testcase classname="runner.RunnerTest" name="runScenario" time="8.185">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError
at stepDefinition.AdvancedSearchSteps.error_for_subject(AdvancedSearchSteps.java:89)
at ✽.an error message for subject should be displayed(file:///C:/WorkSpaces/Sprint2/sprint2/LibraryManagement/src/test/java/features/advancedSearch.feature:65)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="runner.RunnerTest" name="runScenario" time="12.536">
    <failure message="expected:&lt;[Invalid phone message not displayed]&gt; but was:&lt;[Message Sent Successfully]&gt;" type="org.junit.ComparisonFailure">
      <![CDATA[org.junit.ComparisonFailure: expected:<[Invalid phone message not displayed]> but was:<[Message Sent Successfully]>
at org.junit.Assert.assertEquals(Assert.java:117)
at org.junit.Assert.assertEquals(Assert.java:146)
at stepDefinition.ServiceSteps.verifyInvalidPhoneMessage(ServiceSteps.java:92)
at ✽.I should see an error message for invalid phone(file:///C:/WorkSpaces/Sprint2/sprint2/LibraryManagement/src/test/java/features/servicePage.feature:54)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="runner.RunnerTest" name="runScenario" time="11.984">
    <failure message="expected:&lt;[Invalid name message not displayed]&gt; but was:&lt;[Message Sent Successfully]&gt;" type="org.junit.ComparisonFailure">
      <![CDATA[org.junit.ComparisonFailure: expected:<[Invalid name message not displayed]> but was:<[Message Sent Successfully]>
at org.junit.Assert.assertEquals(Assert.java:117)
at org.junit.Assert.assertEquals(Assert.java:146)
at stepDefinition.ServiceSteps.verifyInvalidNameMessage(ServiceSteps.java:107)
at ✽.I should see an error message for invalid name(file:///C:/WorkSpaces/Sprint2/sprint2/LibraryManagement/src/test/java/features/servicePage.feature:81)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="runner.RunnerTest" name="runScenario" time="10.177"/>
  <testcase classname="runner.RunnerTest" name="runScenario" time="12.577"/>
  <testcase classname="runner.RunnerTest" name="runScenario" time="11.049"/>
  <testcase classname="runner.RunnerTest" name="runScenario" time="14.330">
    <failure message="Expected error message not displayed: Please Enter first name" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Expected error message not displayed: Please Enter first name
at org.junit.Assert.fail(Assert.java:89)
at org.junit.Assert.assertTrue(Assert.java:42)
at stepDefinition.LibraryCardStep.an_error_message_should_appear_saying(LibraryCardStep.java:99)
at ✽.an error message should appear saying "Please Enter first name"(file:///C:/WorkSpaces/Sprint2/sprint2/LibraryManagement/src/test/java/features/libraryCard.feature:41)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="runner.RunnerTest" name="runScenario" time="5.896">
    <error message="Failed to instantiate class stepDefinition.ServiceSteps" type="io.cucumber.core.exception.CucumberException">
      <![CDATA[io.cucumber.core.exception.CucumberException: Failed to instantiate class stepDefinition.ServiceSteps
at io.cucumber.core.backend.DefaultObjectFactory.cacheNewInstance(DefaultObjectFactory.java:67)
at io.cucumber.core.backend.DefaultObjectFactory.getInstance(DefaultObjectFactory.java:45)
at io.cucumber.java.AbstractGlueDefinition.invokeMethod(AbstractGlueDefinition.java:47)
at io.cucumber.java.JavaStepDefinition.execute(JavaStepDefinition.java:29)
at io.cucumber.core.runner.CoreStepDefinition.execute(CoreStepDefinition.java:66)
at io.cucumber.core.runner.PickleStepDefinitionMatch.runStep(PickleStepDefinitionMatch.java:63)
at io.cucumber.core.runner.ExecutionMode$1.execute(ExecutionMode.java:10)
at io.cucumber.core.runner.TestStep.executeStep(TestStep.java:84)
at io.cucumber.core.runner.TestStep.run(TestStep.java:56)
at io.cucumber.core.runner.PickleStepTestStep.run(PickleStepTestStep.java:51)
at io.cucumber.core.runner.TestCase.run(TestCase.java:84)
at io.cucumber.core.runner.Runner.runPickle(Runner.java:75)
at io.cucumber.testng.TestNGCucumberRunner.lambda$runScenario$1(TestNGCucumberRunner.java:132)
at io.cucumber.core.runtime.CucumberExecutionContext.lambda$runTestCase$5(CucumberExecutionContext.java:137)
at io.cucumber.core.runtime.RethrowingThrowableCollector.executeAndThrow(RethrowingThrowableCollector.java:23)
at io.cucumber.core.runtime.CucumberExecutionContext.runTestCase(CucumberExecutionContext.java:137)
at io.cucumber.testng.TestNGCucumberRunner.runScenario(TestNGCucumberRunner.java:129)
at io.cucumber.testng.AbstractTestNGCucumberTests.runScenario(AbstractTestNGCucumberTests.java:35)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
Caused by: java.lang.reflect.InvocationTargetException
at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:79)
at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:483)
at io.cucumber.core.backend.DefaultObjectFactory.cacheNewInstance(DefaultObjectFactory.java:53)
... 43 more
Caused by: org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Response code 500. Message: Failed to decode response from marionette 
Host info: host: 'RITAM-BHATTACHA', ip: '192.168.0.103'
Build info: version: '4.22.0', revision: 'c5f3146703*'
System info: os.name: 'Windows 11', os.arch: 'amd64', os.version: '10.0', java.version: '18.0.1.1'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Command: [null, newSession {capabilities=[Capabilities {acceptInsecureCerts: true, browserName: firefox, moz:debuggerAddress: true, moz:firefoxOptions: {binary: C:\Program Files\Mozilla Fi..., prefs: {remote.active-protocols: 3}}}]}]
at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:114)
at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:75)
at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:61)
at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:162)
at org.openqa.selenium.remote.service.DriverCommandExecutor.invokeExecute(DriverCommandExecutor.java:216)
at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:174)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:518)
at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:232)
at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:161)
at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:155)
at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:150)
at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:132)
at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:127)
at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:112)
at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:102)
at driver.DriverSetup.getWebDriver(DriverSetup.java:16)
at pages.ServicePage.<init>(ServicePage.java:16)
at stepDefinition.ServiceSteps.<init>(ServiceSteps.java:8)
at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:67)
... 46 more
]]>
    </error>
  </testcase> <!-- runScenario -->
  <testcase classname="runner.RunnerTest" name="runScenario" time="9.034">
    <error message="Cannot locate option with text: Edition 1
For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Build info: version: &#039;4.22.0&#039;, revision: &#039;c5f3146703*&#039;
System info: os.name: &#039;Windows 11&#039;, os.arch: &#039;amd64&#039;, os.version: &#039;10.0&#039;, java.version: &#039;18.0.1.1&#039;
Driver info: driver.version: unknown" type="org.openqa.selenium.NoSuchElementException">
      <![CDATA[org.openqa.selenium.NoSuchElementException: Cannot locate option with text: Edition 1
For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Build info: version: '4.22.0', revision: 'c5f3146703*'
System info: os.name: 'Windows 11', os.arch: 'amd64', os.version: '10.0', java.version: '18.0.1.1'
Driver info: driver.version: unknown
at org.openqa.selenium.support.ui.Select.selectByVisibleText(Select.java:153)
at pages.AdvancedSearchActions.selectEdition(AdvancedSearchActions.java:35)
at stepDefinition.AdvancedSearchSteps.user_selects_edition(AdvancedSearchSteps.java:30)
at ✽.selects edition as "Edition 1"(file:///C:/WorkSpaces/Sprint2/sprint2/LibraryManagement/src/test/java/features/advancedSearch.feature:54)
]]>
    </error>
  </testcase> <!-- runScenario -->
  <testcase classname="runner.RunnerTest" name="runScenario" time="7.868">
    <failure message="Expected error message not displayed: Please enter a valid email" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Expected error message not displayed: Please enter a valid email
at org.junit.Assert.fail(Assert.java:89)
at org.junit.Assert.assertTrue(Assert.java:42)
at stepDefinition.LibraryCardStep.an_error_message_should_appear_saying(LibraryCardStep.java:99)
at ✽.an error message should appear saying "Please enter a valid email"(file:///C:/WorkSpaces/Sprint2/sprint2/LibraryManagement/src/test/java/features/libraryCard.feature:77)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="runner.RunnerTest" name="runScenario" time="7.620">
    <failure message="Expected error message not displayed: Please Enter the phone" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Expected error message not displayed: Please Enter the phone
at org.junit.Assert.fail(Assert.java:89)
at org.junit.Assert.assertTrue(Assert.java:42)
at stepDefinition.LibraryCardStep.an_error_message_should_appear_saying(LibraryCardStep.java:99)
at ✽.an error message should appear saying "Please Enter the phone"(file:///C:/WorkSpaces/Sprint2/sprint2/LibraryManagement/src/test/java/features/libraryCard.feature:101)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="runner.RunnerTest" name="runScenario" time="12.809"/>
  <testcase classname="runner.RunnerTest" name="runScenario" time="11.640"/>
  <testcase classname="runner.RunnerTest" name="runScenario" time="7.022">
    <failure message="Expected error message not displayed: Please enter a valid phone number" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Expected error message not displayed: Please enter a valid phone number
at org.junit.Assert.fail(Assert.java:89)
at org.junit.Assert.assertTrue(Assert.java:42)
at stepDefinition.LibraryCardStep.an_error_message_should_appear_saying(LibraryCardStep.java:99)
at ✽.an error message should appear saying "Please enter a valid phone number"(file:///C:/WorkSpaces/Sprint2/sprint2/LibraryManagement/src/test/java/features/libraryCard.feature:89)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="runner.RunnerTest" name="runScenario" time="11.239"/>
  <testcase classname="runner.RunnerTest" name="runScenario" time="6.201">
    <failure message="Expected error message not displayed: Please enter the age" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Expected error message not displayed: Please enter the age
at org.junit.Assert.fail(Assert.java:89)
at org.junit.Assert.assertTrue(Assert.java:42)
at stepDefinition.LibraryCardStep.an_error_message_should_appear_saying(LibraryCardStep.java:99)
at ✽.an error message should appear saying "Please enter the age"(file:///C:/WorkSpaces/Sprint2/sprint2/LibraryManagement/src/test/java/features/libraryCard.feature:65)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="runner.RunnerTest" name="runScenario" time="9.795"/>
  <testcase classname="runner.RunnerTest" name="runScenario" time="12.842"/>
  <testcase classname="runner.RunnerTest" name="runScenario" time="11.129"/>
  <testcase classname="runner.RunnerTest" name="runScenario" time="10.772">
    <failure message="expected:&lt;[Invalid email message not displayed]&gt; but was:&lt;[Mail Sent Successfully]&gt;" type="org.junit.ComparisonFailure">
      <![CDATA[org.junit.ComparisonFailure: expected:<[Invalid email message not displayed]> but was:<[Mail Sent Successfully]>
at org.junit.Assert.assertEquals(Assert.java:117)
at org.junit.Assert.assertEquals(Assert.java:146)
at stepDefinition.ServiceSteps.verifyInvalidEmailMessage(ServiceSteps.java:77)
at ✽.I should see an error message for invalid email(file:///C:/WorkSpaces/Sprint2/sprint2/LibraryManagement/src/test/java/features/servicePage.feature:28)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="runner.RunnerTest" name="runScenario" time="8.308"/>
  <testcase classname="runner.RunnerTest" name="runScenario" time="6.019">
    <failure message="Expected error message not displayed: Please enter a valid age" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Expected error message not displayed: Please enter a valid age
at org.junit.Assert.fail(Assert.java:89)
at org.junit.Assert.assertTrue(Assert.java:42)
at stepDefinition.LibraryCardStep.an_error_message_should_appear_saying(LibraryCardStep.java:99)
at ✽.an error message should appear saying "Please enter a valid age"(file:///C:/WorkSpaces/Sprint2/sprint2/LibraryManagement/src/test/java/features/libraryCard.feature:53)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="runner.RunnerTest" name="runScenario" time="13.337"/>
  <testcase classname="runner.RunnerTest" name="runScenario" time="12.117"/>
</testsuite> <!-- runner.RunnerTest -->
